# Generated by Django 5.0.1 on 2024-03-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
