# Generated by Django 5.0.1 on 2024-03-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.IntegerField(default=200),
        ),
    ]
