# Generated by Django 5.0.1 on 2024-03-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0007_userprofile_delete_userdataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='google_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
