# Generated by Django 5.0.1 on 2024-03-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0009_remove_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='google_email',
            new_name='email',
        ),
    ]
