# Generated by Django 5.0.1 on 2024-03-29 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0010_rename_google_email_userprofile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
