# Generated by Django 5.0.3 on 2024-04-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0014_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='html_file',
        ),
    ]
