# Generated by Django 5.0.3 on 2024-04-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0015_remove_userprofile_html_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
