# Generated by Django 5.0.3 on 2024-04-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0017_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
