# Generated by Django 5.0.3 on 2024-04-01 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0019_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
