# Generated by Django 4.2.11 on 2024-04-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0021_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='credit',
            field=models.IntegerField(default=200),
        ),
    ]
