# Generated by Django 4.2.11 on 2024-04-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0023_customuser_p1_customuser_p2_customuser_p3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='p1',
            field=models.URLField(blank=True, default='/editor', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='p2',
            field=models.URLField(blank=True, default='/editor', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='p3',
            field=models.URLField(blank=True, default='/editor', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='p4',
            field=models.URLField(blank=True, default='/editor', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='p5',
            field=models.URLField(blank=True, default='/editor', null=True),
        ),
    ]
