# Generated by Django 4.2.11 on 2024-04-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0024_alter_customuser_p1_alter_customuser_p2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='p1',
            new_name='t1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='p5',
        ),
        migrations.AddField(
            model_name='customuser',
            name='c1',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='c2',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='c3',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='c4',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='c5',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='t2',
            field=models.URLField(blank=True, default='/editor', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='t3',
            field=models.URLField(blank=True, default='/editor', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='t4',
            field=models.URLField(blank=True, default='/editor', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='t5',
            field=models.URLField(blank=True, default='/editor', null=True),
        ),
    ]
