# Generated by Django 4.2.11 on 2024-04-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0025_rename_p1_customuser_t1_remove_customuser_p2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='t1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='t2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='t3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='t4',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='t5',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
