# Generated by Django 4.2.11 on 2024-04-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quviapi', '0045_alter_customuser_c1_alter_customuser_c2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='c1',
            field=models.TextField(max_length=1073741824, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='c2',
            field=models.TextField(max_length=1073741824, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='c3',
            field=models.TextField(max_length=1073741824, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='c4',
            field=models.TextField(max_length=1073741824, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='c5',
            field=models.TextField(max_length=1073741824, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='t1',
            field=models.TextField(max_length=1073741824, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='t2',
            field=models.TextField(max_length=1073741824, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='t3',
            field=models.TextField(max_length=1073741824, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='t4',
            field=models.TextField(max_length=1073741824, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='t5',
            field=models.TextField(max_length=1073741824, null=True),
        ),
    ]
